apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: "{{_SERVICE}}"
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/invoker-iam-disabled: 'true'
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Custom
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - name: "{{_SERVICE}}"
          image: "{{_IMAGE}}"
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: CONFIG_YAML
              value: /configs/config.yaml
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /configs
          livenessProbe:
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
          startupProbe:
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
      volumes:
        - name: config
          secret:
            secretName: "{{_SERVICE}}-config"
            items:
              - key: latest
                path: config.yaml

