substitutions:
  _SERVICE: service # TODO: service name
  _REGION: asia-southeast2 # TODO: region
  _REGISTRY: docker # TODO: registry
  _IMAGE: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY}/${_SERVICE}
  _CHART: oci://${_REGION}-docker.pkg.dev/${PROJECT_ID}/helm/cloud-run

steps:
  - name: gcr.io/kaniko-project/executor
    args:
      - --context=.
      - --dockerfile=ci/Dockerfile
      - --destination=${_IMAGE}:latest
      - --destination=${_IMAGE}:${BUILD_ID}
      - --cache=true
      - --cache-ttl=24h

  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --project=${PROJECT_ID}
      - --region=${_REGION}
      - --image=${_IMAGE}:${BUILD_ID}

options:
  dynamicSubstitutions: true
  automapSubstitutions: true
